Add metrics timer for CompilePost
open-policy-agent/opa pull request #3097
Opened 2021-01-25 11:12 UTC by jkbschmid

Hi all!

Solves https://github.com/open-policy-agent/opa/issues/3096.
This change adds a `server_handler` timer to the metrics for any POSTs to `/v1/compile`.

So `curl -X POST localhost:8181/v1/compile?metrics ..` will result in:
```
...
"metrics": {
    "timer_rego_partial_eval_ns": 145020,
    "timer_rego_query_compile_ns": 86415,
    "timer_rego_query_parse_ns": 56104,
    "timer_server_handler_ns": 377557  #this line is new
  }
```

2021-01-25 12:04 UTC, srenatus reviewed
Thanks for your contribution! 🎉 

I think the code change itself is fine. I wonder if it would be worth adding a test case to https://github.com/open-policy-agent/opa/blob/38d8161903d26e75b9876443dc06f772326970a5/test/e2e/metrics/metrics_test.go; but I haven't checked our current coverage for metrics responses 🤔

2021-01-26 08:10 UTC, jkbschmid commented
Right now, only the metrics for V1DataGETs are tested. If you like, I can add a test case for V1PostCompile as well.

2021-01-26 08:50 UTC, srenatus commented
That would be great, thank you!

2021-01-26 11:02 UTC, jkbschmid commented
I had to add an additional method `assertCompileInstrumentationMetricsInMap` that tests for all metrics that are currently recorded. Not sure whether these are actually the metrics we want to have, but I think this could be solved in another PR.

2021-01-26 12:21 UTC, srenatus submitted a review, later dismissed
Thanks a lot for tackling tests here, too! 👏

2021-01-26 12:21 UTC, srenatus commented on test/e2e/metrics/metrics_test.go
> +		// "timer_query_compile_stage_rewrite_to_capture_value_ns",
Let's just remove this line? 🤔

2021-01-26 13:03 UTC, jkbschmid commented
Thanks for the review and the quick responses! 🙂

2021-01-26 13:22 UTC, srenatus requested changes
Thank you!

2021-01-26 13:23 UTC, srenatus approved these changes
Misclicked 😄 Thank you!

2021-01-26 13:24 UTC, merged