Adds runtime() to Go SDK
open-policy-agent/opa pull request #4063
Opened 2021-11-29 14:05 UTC by oren-zohar

Signed-off-by: orenzohar <oren.zohar@elastic.co>

Adds Runtime(Context) function to Go SDK.
Fixes #4050

2021-11-30 01:15 UTC, tsandall requested changes
I think what we need to do is similar to https://github.com/open-policy-agent/opa/blob/main/runtime/runtime.go#L283:

* Call the internal/runtime.Term function to generate the runtime information structure on SDK init/reconfigure
* Optional: extend the runtime info to indicate the environment is an SDK and not OPA proper (I don't have an immediate use case for this, but I could see it being useful...) We'd have to figure out the right schema for that... could just leave it out for now.
* Pass the term to the evaluator whenever eval is run

2021-11-30 01:15 UTC, tsandall commented on sdk/opa.go
> +func (opa *OPA) Runtime(ctx context.Context) (*runtime.Runtime, error) {
I don't see a need for this function and I'd rather not extend the OPA SDK API if possible.

2021-12-07 17:19 UTC, tsandall commented
@oren-zohar this looks good! We just need a test case to go along with it. Once the test case is added the commits have been squashed we can merge this.

2021-12-09 08:46 UTC, oren-zohar commented
@tsandall added a test

2021-12-09 12:10 UTC, srenatus approved these changes
LGTM. Would you mind squashing your commits into one? We should be able to get this in quick then 🚀

2021-12-09 16:36 UTC, tsandall approved these changes
LGTM

2021-12-09 16:36 UTC, merged